In [1]:
import pandas as pd
import numpy as np

# Step 1: Data Loading and Initial Exploration
##	Load all datasets using Pandas

In [100]:
# load dimensions
df_customers = pd.read_csv('dataset/customers.csv')
df_location = pd.read_csv('dataset/location.csv')
df_sellers = pd.read_csv('dataset/sellers.csv')
df_products = pd.read_csv('dataset/products.csv')
df_cat_trans = pd.read_csv('dataset/category_translation.csv')



# load facts
df_orders = pd.read_csv('dataset/orders.csv')
df_order_item = pd.read_csv('dataset/order_item.csv')
df_payments = pd.read_csv('dataset/payments.csv')
df_reviews = pd.read_csv('dataset/reviews.csv')

## Inspect structure using .head(), .info(), .describe()

In [3]:
# inspect fact data - orders

df_orders.head()
df_orders.info()
df_orders.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-04-11 10:48:14,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-08 23:38:46,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [4]:
# inspect fact data - order_item

df_order_item.head()
df_order_item.info()
df_order_item.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [5]:
# inspect fact data - payments

df_payments.head()
df_payments.info()
df_payments.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [6]:
# inspect fact data - reviews

df_reviews.head()
df_reviews.info()
df_reviews.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [7]:
# inspect one dimension data - customers

df_customers.head()
df_customers.info()
df_customers.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [8]:
df_location.head()
df_location.info()
df_location.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

In [9]:
df_sellers.head()
df_sellers.info()
df_sellers.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

In [10]:
df_products.head()
df_products.info()
df_products.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [11]:
df_cat_trans.head()
df_cat_trans.info()
df_cat_trans.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

## •	Identify primary and foreign keys

In [12]:
#location

print("Total rows:", df_location.shape[0])
print("Unique rows:", df_location.drop_duplicates().shape[0])

df_location_cleaned = df_location.copy().drop_duplicates()

print("Cleaned Total rows:", df_location_cleaned.shape[0])
print("Unique Key Check:", df_location_cleaned[['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng']].duplicated().sum())

df_location_cleaned.head()
# There is no primary key/foreign key
# we need to further investigate and clean this dataset from duplicates

Total rows: 1000163
Unique rows: 738332
Cleaned Total rows: 738332
Unique Key Check: 18178

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [13]:
# customers
print("Total rows:", len(df_customers))
print("Unique customer_id:", df_customers['customer_id'].nunique())

df_customers.head()
# primary key - customer_id
# foreign_key --> customer_zip_code_prefix to geolocation_zip_code_prefix of location

Total rows: 99441
Unique customer_id: 99441

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [14]:
# sellers
print("Total rows:", len(df_sellers))
print("Unique seller_id:", df_sellers['seller_id'].nunique())

# primary key --> seller_id
# foreign_key --> seller_zip_code_prefix to geolocation_zip_code_prefix of df_location
df_sellers.head()

Total rows: 3095
Unique seller_id: 3095

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [15]:
# category_translation
print("Total rows:", len(df_cat_trans))
print("Unique product_category_name:", df_cat_trans['product_category_name'].nunique())

# primary key --> product_category_name
# foreign_key --> none 
df_cat_trans.head()

Total rows: 71
Unique product_category_name: 71

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [16]:
# products
print("Total rows:", len(df_products))
print("Unique product_id:", df_products['product_id'].nunique())

# primary key --> product_id
# foreign_key --> product_category_name 
df_products.head()

Total rows: 32951
Unique product_id: 32951

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [17]:
# orders

print("Total rows:", len(df_orders))
print("Unique product_id:", df_orders['order_id'].nunique())

# primary key --> order_id
# foreign_key --> customer_id to customers 
df_orders.head()

Total rows: 99441
Unique product_id: 99441

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [18]:
# order_item 

print("Total rows:", len(df_order_item))
#print("Unique order_id:", df_order_item['order_id'].nunique())
print("Unique Key Check:", df_order_item[['order_id', 'order_item_id']].duplicated().sum())


# primary key --> composite of order_id, order_item_id
# foreign_key --> order_id to orders table, product_id to products table, seller_id to sellers table

df_order_item.head()

Total rows: 112650
Unique Key Check: 0

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [19]:
# payments

print("Total rows:", len(df_payments))
#print("Unique order_id:", df_payments['order_id'].nunique())
print("Unique Key Check:", df_payments[['order_id', 'payment_sequential', 'payment_type']].drop_duplicates().shape[0])

# primary key --> 'order_id', 'payment_sequential', 'payment_type'
# foreign_key --> order_id to orders 
df_payments.head()

Total rows: 103886
Unique Key Check: 103886

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [20]:
# reviews

print("Total rows:", len(df_reviews))
#print("Unique review_id:", df_reviews['review_id'].nunique())
print("Unique Key Check:", df_reviews[['review_id', 'order_id']].drop_duplicates().shape[0])

# primary key --> 'review_id', 'order_id'
# foreign_key --> order_id to orders 
df_reviews.head()

Total rows: 99224
Unique Key Check: 99224

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

# •	Understand relationships between tables

In [21]:
# current structure is liek a snowflake schema

# inside dimensions
# product dimension is connected again to category_translation dimension
# customer dimension is connected to location dimension
# sellers dimenstion is connected to location dimension

# not all dimension is connected to fact
# product is connected to fact(order) via order_item
# seller is connected to fact(order) via order_item

# so we merge everything into a single dataframe and make it a star schema requivalent in ML

# Step 2: Data Cleaning and Preprocessing

## •	Handle missing values appropriately

In [33]:
# check missing values
def check_missing_values(df):
    print('Check for Nan------>')
    print(df.isna().sum())
    check_empty = (df.select_dtypes(include='object')
                    .apply(lambda x: x.str.strip())
                    .eq('')
                    .sum())
    print('Check for Empty String------>')    
    print(check_empty)

In [35]:
check_missing_values(df_customers) # no missing value

Check for Nan------>
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
Check for Empty String------>
customer_id           0
customer_unique_id    0
customer_city         0
customer_state        0
dtype: int64

In [36]:
check_missing_values(df_location) # no missing value

Check for Nan------>
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
Check for Empty String------>
geolocation_city     0
geolocation_state    0
dtype: int64

In [37]:
check_missing_values(df_sellers) # no missing value

Check for Nan------>
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
Check for Empty String------>
seller_id       0
seller_city     0
seller_state    0
dtype: int64

In [74]:
check_missing_values(df_products) # missing value

Check for Nan------>
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
Check for Empty String------>
product_id               0
product_category_name    0
dtype: int64

In [72]:
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [76]:
# drop data where very small number of missing values
df_products = df_products.dropna(subset=['product_weight_g', 'product_length_cm', 'product_width_cm', 'product_height_cm'])

# product_category_name is important categoricl value and we will fill with unknown
df_products['product_category_name'] = df_products['product_category_name'].fillna('unknown')

# product_photos_qty is number, we can fill with 0
df_products['product_photos_qty'] = df_products['product_photos_qty'].fillna(0)

# product_name_lenght and product_description_lenght are derived column, for unknown categories we fill up with 0, 
# if it was random, we could have used mean/median
df_products['product_name_lenght'] = df_products['product_name_lenght'].fillna(0)
df_products['product_description_lenght'] = df_products['product_description_lenght'].fillna(0)

In [77]:
check_missing_values(df_products) # missing value

Check for Nan------>
product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64
Check for Empty String------>
product_id               0
product_category_name    0
dtype: int64

In [79]:
check_missing_values(df_cat_trans) # no missing value

Check for Nan------>
product_category_name            0
product_category_name_english    0
dtype: int64
Check for Empty String------>
product_category_name            0
product_category_name_english    0
dtype: int64

In [86]:
print('Length: ', df_orders.shape[0])
check_missing_values(df_orders) # missing value
# we cannot drop this columns as missing value means order not approved/ not delivered
# we can create flags

Length:  99441
Check for Nan------>
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
Check for Empty String------>
order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

In [87]:
print('Length: ', df_order_item.shape[0])
check_missing_values(df_order_item) # no missing value

Length:  112650
Check for Nan------>
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
Check for Empty String------>
order_id               0
product_id             0
seller_id              0
shipping_limit_date    0
dtype: int64

In [88]:
print('Length: ', df_payments.shape[0])
check_missing_values(df_payments) # no missing value

Length:  103886
Check for Nan------>
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
Check for Empty String------>
order_id        0
payment_type    0
dtype: int64

In [101]:
print('Length: ', df_reviews.shape[0])
check_missing_values(df_reviews) # missing value

Length:  99224
Check for Nan------>
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
Check for Empty String------>
review_id                   0
order_id                    0
review_comment_title        2
review_comment_message     27
review_creation_date        0
review_answer_timestamp     0
dtype: int64

In [106]:
# replace empty strings
df_reviews['review_comment_title'] = df_reviews['review_comment_title'].str.strip().replace('', None)
df_reviews['review_comment_message'] = df_reviews['review_comment_message'].str.strip().replace('', None)

# we cannot put mode or random reviews, we create new feature
df_reviews['has_comments'] = df_reviews['review_comment_title'].notnull()
df_reviews['has_message'] = df_reviews['review_comment_message'].notnull()

In [107]:
check_missing_values(df_reviews) # missing value

Check for Nan------>
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87658
review_comment_message     58274
review_creation_date           0
review_answer_timestamp        0
has_comments                   0
has_message                    0
dtype: int64
Check for Empty String------>
review_id                  0
order_id                   0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64